logging:
  level:
    liquibase: DEBUG
    
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:loyalty;DB_CLOSE_DELAY=-1;
    username=: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  h2:
    console:
      enabled: true

app:
  max-date-range: 3
  loyalty:
        - description: 'Above 50, under 100, then give 1 point'
          minimum: 50
          maximum: 100
          amount: 1
        - description: 'Above 100, then give 2 point'
          minimum: 100
          maximum: 200
          amount: 2